FROM node:22.12-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist/cspoint-frontend/browser /usr/share/nginx/html
